stages:
  - test
  - deploy

Test:
  stage: test
  script:
    - apk add --no-cache python3 py3-pip
    - pip3 install --break-system-packages --no-cache-dir -r requirements.txt
    - python -m unittest test.py

Deploy:
  stage: deploy
  script:
    - echo "Deployment..."
  only:
    - develop
